[package]
name = "rusty-bunny"
version = "0.1.0"
authors = ["Joe Previte <jprevite@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
percent-encoding = "2.1.0"
